### ISSUE TITLE
Does this work with the Utility Classes?

### ISSUE THREAD

**Issue by motleydev** [jlengstorf/gatsby-tailwind-demo#4]
As far as I can tell this doesn't allow you to use the tailwind directives, is that correct?

https://tailwindcss.com/docs/installation#3-use-tailwind-in-your-css

**Comment by mattbag** [comment]
I had the same question, I think using those global defeats the purpose of having emotion.

If you really need global classes there's the other example with purgecss.

**Comment by jlengstorf** [comment]
Hey, @motleydev — I did a tiny bit of testing and it doesn't appear that they work. 

This would be a better issue for https://github.com/bradlc/babel-plugin-tailwind-components, since that's where the support would need to be added.

I'm going to close this, but feel free to tag me in the upstream issue if you think I can help.
