### ISSUE TITLE
emotion 10 support?

### ISSUE THREAD

**Issue by ovsw** [jlengstorf/gatsby-tailwind-demo#7]
When following readme to use your setup in my own gatsby 2 project, I get error: 
```
Error: The package "react-emotion" has been replaced by "@emotion/styled" in version 10. See https://emotion.sh/docs/migrating-to-emotion-10 for more information on migrating.
```
When replacing `import styled from 'react-emotion'` with `import styled from '@emotion/styled'` I get eeror:
```
ReferenceError: tw is not defined
```
How to make it work with emotion 10?

**Comment by jlengstorf** [comment]
Hi @ovsw! I'm not really sure, to be completely honest. Since this is just a usage example and not the actual project, this would probably be a better question in the [bradlc/babel-plugin-tailwind-components](https://github.com/bradlc/babel-plugin-tailwind-components) repo.

I'm going to close this issue, but if you find a solution and want to PR a change into this example, that would be _hugely_ appreciated.

Thanks!
